version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tacobell-cart"
aws_region = "us-east-2"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "StackName=\"tacobell-cart\" AWSRegion=\"us-east-2\" APIGatewayStageName=\"cart\" LambdaDeploymentRole=\"arn:aws:iam::525308554527:role/service-role/getCartValues-role-dfo6y0qr\""